name: Composite Action Demo

on: [workflow_dispatch]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Run Composite Action
        uses: ./.github/actions/composite-action@main
