name: Composite Action Demo

on: [workflow_dispatch]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Run Composite Action
        uses: ./.github/actions/composite-action
        
      - name: Write Summary
        run: |
          echo '# Summary' >> $GITHUB_STEP_SUMMARY
          echo 'This is the summary :ship:' >> $GITHUB_STEP_SUMMARY
