name: Secrets Demo

on: [workflow_dispatch]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "My Secret ${{ secrets.MY_REPO_SECRET }}"
      - run: echo "My Variable ${{ secrets.MY_REPO_VAR }}"
